name = "Hexxycraft 2"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0816a3a8d877e7fc604026438c0789cee929d85ae431861c986794dbfa29e201"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
