name = "Hexxycraft 2"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f1a2d0bd40aaa3f42bfc77ca9c3d5755e3e95dbf6407d2dd8b17df2ffc3831e"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
