name = "Hexxycraft 2"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1effc3901a1cc375afa7cb77bf67a8cb0689da532bb5de8c23f7002bedbd8d6e"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
